<?php

// LOGGING CONFIGURATION
const LOG_PATH = '';

// DATABASE SETTINGS
const DB_HOST = '';
const DB_NAME = '';
const DB_USER = '';
const DB_PASS = '';


// MESSENTE VERIFY SETTINGS
const MESSENTE_API_USER = '';
const MESSENTE_API_PASS = '';
const MESSENTE_VERIFY_VERSION = '';
const MESSENTE_VERIFY_LOGIN_CALLBACK_URL = '';
const MESSENTE_VERIFY_REGISTER_CALLBACK_URL = '';

